### ISSUE TITLE
Some Questions

### ISSUE THREAD

**Issue by le1smo** [williamtang/logseq-blog#1]
- logseq的皮肤用的是这个吗？[dev](https://github.com/pengx17/logseq-dev-theme)
- blog怎么做的？🙏

多谢

**Comment by williamtang** [comment]
> * logseq的皮肤用的是这个吗？[dev](https://github.com/pengx17/logseq-dev-theme)
> * blog怎么做的？🙏
> 
> 多谢

sorry for replying so late...
yeah, I used dev theme for the published logseq page.

as to the 2nd question,
- firstly you need to set page export to public in logseq setting
- then push exported html files to github (as github page)
- the last step, assign a personal domain with github page

hope to help you.

**Comment by le1smo** [comment]
thanks for your answer
